name: Model Promotion (Staging → Prod with Approval)

on:
  repository_dispatch:
    types: [model-approved]

permissions:
  id-token: write
  contents: read

jobs:
  call-real-one:
    uses: GoormCloud-3/FinGuard-Flask/.github/workflows/model-promotion.yml@suhyun
    with:
      model_package_arn: ${{ github.event.client_payload.model_package_arn }}
