name: Model Promotion (Staging → Prod with Approval)

on:
  repository_dispatch:
    types: [model-approved]

permissions:
  id-token: write
  contents: read

jobs:
  call-real-one:
    uses: <OWNER>/<REPO>/.github/workflows/real.yml@your-feature-branch  # ★ 브랜치 지정
    with:
      model_package_arn: ${{ github.event.client_payload.model_package_arn }}
