name: Run Anything (Manual Orchestrator)

on:
  workflow_dispatch:
    inputs:
      target:
        description: "실행 대상"
        required: true
        type: choice
        options:
          - infra-iam-lambda
          - pipeline-export-apply
          - serving-image
          - destroy-infra
          - destroy-pipeline
          - alarms-apply
          - alarms-destroy
          - baseline-generate
      environment:
        description: "환경(dev/prod 등)"
        required: false
        default: "dev"
      tag:
        description: "serving-image용 태그(옵션)"
        required: false
        default: ""
      confirm:
        description: "Destroy/Clean 시 EXACTLY 입력: DELETE"
        required: false
        default: ""
      dataset_s3:
        description: "학습데이터 S3 URI (CSV/JSONL)"
        required: false
        default: ""
      baseline_prefix:
        description: "Baseline 저장 S3 prefix (끝에 /)"
        required: false
        default: ""
      instance_type:
        description: "Processing 인스턴스"
        required: false
        default: "ml.m5.xlarge"

permissions:
  id-token: write 
  contents: read

jobs:
  call-infra:
    if: ${{ inputs.target == 'infra-iam-lambda' }}
    uses: ./.github/workflows/infra-iam-lambda.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  call-pipeline:
    if: ${{ inputs.target == 'pipeline-export-apply' }}
    uses: ./.github/workflows/pipeline-export-apply.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  call-serving:
    if: ${{ inputs.target == 'serving-image' }}
    uses: ./.github/workflows/serving-image.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit

  call-destroy-infra:
    if: ${{ inputs.target == 'destroy-infra' }}
    uses: ./.github/workflows/infra-destroy.yml
    with:
      environment: ${{ inputs.environment }}
      confirm: ${{ inputs.confirm }}
    secrets: inherit

  call-destroy-pipeline:
    if: ${{ inputs.target == 'destroy-pipeline' }}
    uses: ./.github/workflows/pipeline-destroy.yml
    with:
      environment: ${{ inputs.environment }}
      confirm: ${{ inputs.confirm }}
    secrets: inherit

  call-alarms-apply:
    if: ${{ github.event.inputs.target == 'alarms-apply' }}
    uses: ./.github/workflows/alarms-apply.yml
    with:
      environment: ${{ inputs.environment }}
      mode: apply
    secrets: inherit

  call-alarms-destroy:
    if: ${{ github.event.inputs.target == 'alarms-destroy' }}
    uses: ./.github/workflows/alarms-destroy.yml
    with:
      environment: ${{ inputs.environment }}
      confirm: ${{ inputs.confirm }}
    secrets: inherit

  call-baseline-generate:
    if: ${{ inputs.target == 'baseline-generate' }}
    uses: ./.github/workflows/model-baseline.yml
    with:
      dataset_s3: ${{ inputs.dataset_s3 }}
      baseline_prefix: ${{ inputs.baseline_prefix }}
      instance_type: ${{ inputs.instance_type }}
    secrets: inherit
